# -*- coding: utf-8 -*-
"""functionalPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCGd0Yxwd6IgGGsQ9T6hHsvEJM8L9p05
"""

wideLink="https://github.com/MagallanesAtAlacip/datafiles/raw/main/covid_fatalities2021_yearly_wide.csv"

import pandas as pd

covidPeru_wide=pd.read_csv(wideLink)
covidPeru_wide.head()

covidPeru_wide.info()

import matplotlib.pyplot as plt

# Separate the numeric data from the index column:
# covidPeru_wide.drop(columns=["PROVINCIA"])

# plt.figure(figsize=(12, 6))

# Matplotlib's boxplot handles wide data columns perfectly
plt.boxplot(covidPeru_wide.drop(columns=["PROVINCIA"]).values,
            tick_labels=covidPeru_wide.drop(columns=["PROVINCIA"]).columns); ##;

## details
# Rotate labels so they don't overlap
# plt.xticks(rotation=45, ha="right")
# plt.title("Distribution of Cases by Demographic Group")
# plt.ylabel("Number of Cases")
# plt.tight_layout()

# plt.show() # not strictly needed in notebooks...but recommended

# import matplotlib.ticker as ticker

# Pass vert=False to make the boxplot horizontal
covidPeru_wide.boxplot(vert=False)

# this dependd if you flip or not (only one of these!)
plt.xscale('log')
# plt.yscale('log')

# Clean up the axis formatting
# ax = plt.gca()
# ax.xaxis.set_major_formatter(ticker.ScalarFormatter())
# ax.xaxis.set_minor_formatter(ticker.NullFormatter()) # Hides annoying minor scientific labels
# ax.ticklabel_format(style='plain', axis='x')          # Forces plain numbers

# plt.title("Case Distributions (Wide Data)")
# # Change ylabel to xlabel since the data is now on the horizontal axis
# plt.xlabel("Cases")

# plt.tight_layout()

# plt.show()

